#!/bin/bash

echo "Oki! Preparing to build a Vanilla Arch ISO using latest monthly profile!" && sleep 1.3
echo

	profile=releng
	profiledef=$profile/profiledef.sh
	user=$(whoami)
	outDir=ISO
	buildDir=Build

cd

echo "First abs will check to see if you have used this option before."
echo "Should abs find the directory this option uses, abs will preserve it so that any older ISO's will not be lost."
echo "The build directory however will be destroyed and remade."

if [[ -d Arch-Vanilla ]]; then
	echo "abs has ${fgCyan}found${txReset} the Arch-Vanilla directory this option uses!" && sleep 1.3
	echo "abs will now change into that directory and empty the build folder before moving forward."
	sudo rm -rf Arch-Vanilla/Build && mkdir Arch-Vanilla/Build
else
	echo "abs could ${fgRed}not${txReset} locate the directory this option uses. abs will now create it." && sleep 1.3
	mkdir Arch-Vanilla
	mkdir Arch-Vanilla/ISO
	mkdir Arch-Vanilla/Build
	echo "Arch-Vanilla directory has been created and within it exist folders labeled ISO and Build."
	echo "abs will now change into the Arch-Vanilla directory and move onto the next step."
fi

cd Arch-Vanilla

echo
echo "abs will now check if you have the latest archiso so that we only build the newest ISO possible."

checkInternetConnection
isArchisoUpToDate
valenRepoAdder

echo "abs will now copy over the Latest Montly Arch Profile into this directory."
cp -rf /usr/share/archiso/configs/releng/ releng/
sudo chown -R $user releng

echo
echo "We are all setup to build the latest Vanilla Arch Monthly ISO. Lets Begin!"
echo "ISO will be found in a folder within this directory labeled ISO!"
echo "Build folder will be labeled Build!"
echo "This will take a bit so perhaps make some coffee!"

sudo mkarchiso -v -w $buildDir -o $outDir $profile
sudo chown -R $user $buildDir
sudo chown -R $user $outDir
